language: node_js
node_js:
- '12.0'
branches:
  only:
  - master
addons:
  chrome: stable
before_script:
- npm install -g @angular/cli
script:
- npm install
- npm run build:prod
- ng test --watch=false
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "VBl0kGgwGYurRn3bFNncEc9bXWly1lWwH169zG9TjPrx4UevgaePlxP9ROvMEaO/CC1BHXZS7DohO+588etKQNjyxTQnoQK2jMYVNjMrnR3v5UKdKFq4LiUwCIIdiONgBOny2+jP/BMVraPo/5rxhhEEEwDyvk8XM1/0QL5L7r77+LtrlYQx09LIlgJM1Hda/IatTCkWxRr9lPPn1R2fsqKWstjPXRQeIMWMCxASEQCmTzH2ZO2xzG6Uc+6WdgGOfs2jpNuh1jN3kTC+GU0ZDZFGNdO08Tzvda/WPkTngLTn9cp6adHSuOuVUK2VsE2I92ggpp1zuELM+bRSt7b8VXZx+t2zmDmrou213Ke1YDVnDhOHFRC3hCpP7GJUPjXMAAPLW94lxyhyeU+37H/WBaGPK8WZjPDIn5RfQPVvcu0YxqW4mOesvBEgqOiQSgP/2J17POZvYTG8uq+KGGufOkjijf/B4BYzsM1ep0+S8R56s3apObXL5QrOA/1sTQdR0c3qjja2anVafEEfF2e2t4SgQLXv40gB3BPiuDtaDnEmO9CDvdQtM43EOv+BgmaTlI0geNFO9/n12t+ZybROmmhexjqy/lpZ6K020cd1Vwh6WVL0bnrSgnqP90y8zWM3lEWVyDL/SXW7rpiTy60PW6xP1s7pwXq1IwN4FV4InSQ="
